<?php

namespace Database\Seeders;

use App\Models\Kelurahan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kelurahan = [
            ['kelurahan' => 'AMBAKIANG', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'AWAYAN', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'AWAYAN HILIR', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'BADALUNGGA', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'BADALUNGGA HILIR', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'BARAMBAN', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'BARU', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'BIHARA', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'BIHARA HILIR', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'KEDONDONG', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'MERAH', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'MUARA JAYA', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'NUNGKA', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'PIYAIT', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'PUDAK', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'PULANTAN', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'PUTAT BASIUN', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'SEI PUMPUNG', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'SIKONTAN', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'TANGALIN', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'TUNDAKAN', 'kecamatan' => 'AWAYAN'],
            ['kelurahan' => 'TUNDI', 'kecamatan' => 'AWAYAN'],

            ['kelurahan' => 'BAKUNG', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'BANUA HANYAR', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'BATUMANDI', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'BUNGUR', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'GUHA', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'GUNUNG MANAU', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'HAMPA RAYA', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'KARUH', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'KASAI', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'LOK BATU', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'MAMPARI', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'MANTIMIN', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'MUNJUNG', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'PELAJAU', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'RIWA', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'TARIWIN', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'TELUK MESJID', 'kecamatan' => 'BATU MANDI'],
            ['kelurahan' => 'TIMBUN TULANG', 'kecamatan' => 'BATU MANDI'],

            ['kelurahan' => 'ANIUNGAN', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'BANGKAL', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'BARUH PANYAMBARAN', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'BINJAI PUNGGAL', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'BINJU', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'BINUANG SANTANG', 'kecamatan' => 'HALONG'],
            ['kelurahan' => ' BUNTU PILANDUK', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'GUNUNG RIUT', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'HALONG', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'HAUWAI', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'KAPU', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'KARYA', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'LIYU', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'MAMANTANG', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'MAMIGANG', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'MANTUYAN', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'MARAJAI', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'MAUYA', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'PADANG RAYA', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'PUYUN', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'SUMBER AGUNG', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'SURYATAMA', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'TABUAN', 'kecamatan' => 'HALONG'],
            ['kelurahan' => 'UREN', 'kecamatan' => 'HALONG'],

            ['kelurahan' => ' BATA', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'BUNTU KARAU', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'GALUMBANG', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'GULINGGANG', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'HAMARUNG', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'HUKAI', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'JUAI', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'LALAYAU', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'MARIAS', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'MIHU', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'MUARA NINIAN', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'MUNGKUR UYAM', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'PAMURUS', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'PANIMBAAN', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'SIRAP', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'SUMBER REJEKI', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'SUNGAI BATUNG', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'TAWAHAN', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'TELUK BAYUR', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'TIGARUN', 'kecamatan' => 'JUAI'],
            ['kelurahan' => 'WONOREJO', 'kecamatan' => 'JUAI'],

            ['kelurahan' => 'BATU MERAH', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'HILIR PASAR', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'JIMAMUN', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'JUNGKAL', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'KANDANG JAYA', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'KUPANG', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'KUSAMBI HILIR', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'KUSAMBI HULU', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'LAJAR', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'LAMPIHONG KANAN', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'LAMPIHONG KIRI', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'LAMPIHONG SELATAN', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'LOK HAMAWANG', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'LOK PANGINANGAN', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'MATANG HANAU', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'MATANG LURUS', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'MUNDAR', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'PANAITAN', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'PIMPING', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'PUPUYUAN', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'SIMPANG TIGA', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'SUNGAI AWANG', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'SUNGAI TABUK', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'TAMPANG', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'TANAH HABANG KANAN', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'TANAH HABANG KIRI', 'kecamatan' => 'LAMPIHONG'],
            ['kelurahan' => 'TELUK KARYA', 'kecamatan' => 'LAMPIHONG'],

            ['kelurahan' => 'BABAYAU', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'BALANG', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'BALIDA', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'DAHAI', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'HUJAN MAS', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'KALAHIANG', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'LAMIDA BAWAH', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'LASUNG BATU', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'LAYAP', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'LOK BATUNG', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'MANGKAYAHU', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'MURUNG ILUNG', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'PARAN', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'PARINGIN KOTA', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'PARINGIN TIMUR', 'kecamatan' => 'PARINGIN'],
            ['kelurahan' => 'SUNGAI KETAPI', 'kecamatan' => 'PARINGIN'],

            ['kelurahan' => 'BARUH BAHINU DALAM', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'BARUH BAHINU LUAR', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'BATU PIRING', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'BINJAI', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'BUNGIN', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'GALUMBANG', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'HALUBAU', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'HALUBAU UTARA', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'INAN', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'LINGSIR', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'MARADAP', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'MURUNG ABUIN', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'MURUNG JAMBU', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'PANGGUNG', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'TARANGAN', 'kecamatan' => 'PARINGIN SELATAN'],
            ['kelurahan' => 'TELAGA PURUN', 'kecamatan' => 'PARINGIN SELATAN'],

            ['kelurahan' => 'AJUNG', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'AUH', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'DAYAK PITAP', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'GUNUNG BATU', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => "JU'UH", 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'KAMBIYAIN', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'LANGKAP', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'MAYANAU', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'SIMPANG BUMBUAN', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'SIMPANG NADONG', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'SUNGSUM', 'kecamatan' => 'TEBING TINGGI'],
            ['kelurahan' => 'TEBING TINGGI', 'kecamatan' => 'TEBING TINGGI'],

            ['kelurahan' => 'ALUH ALUH BESAR', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'ALUH ALUH KECIL', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'ALUH ALUH KECIL MUARA', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'BAKAMBAT', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'BALIMAU', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'BUNIPAH', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'HANDIL BARU', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'HANDIL BUJUR', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'KUIN BESAR', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'KUIN KECIL', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'LABAT MUARA', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'PEMURUS', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'PODOK', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'PULANTAN', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'SIMPANG WARGA', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'SIMPANG WARGA DALAM', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'SUNGAI MUSANG', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'TANIPAH', 'kecamatan' => 'ALUH ALUH'],
            ['kelurahan' => 'TERAPU', 'kecamatan' => 'ALUH ALUH'],

            ['kelurahan' => 'APUAI', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'ARANIO', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'ARTAIN', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'BELANGIAN', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'BENUA RIAM', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'BUNGLAI', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'KALAAN', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => "PA'AU", 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'RANTAU BALAI', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'RANTAU BUJUR', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'TIWINGAN BARU', 'kecamatan' => 'ARANIO'],
            ['kelurahan' => 'TIWINGAN LAMA', 'kecamatan' => 'ARANIO'],

            ['kelurahan' => 'ASTAMBUL KOTA', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'ASTAMBUL SEBERANG', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'BANUA ANYAR DANAU SALAK', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'BANUA ANYAR SUNGAI TUAN', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'DANAU SALAK', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'JATI BARU', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'KALIUKAN', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'KELAMPAIAN ILIR', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'KELAMPAIAN TENGAH', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'KELAMPAIAN ULU', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'LIMAMAR', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'LOK GABANG', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'MUNGGU RAYA', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'PASAR JATI', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'PEMATANG HAMBAWANG', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'PINGARAN ILIR', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'PINGARAN ULU', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'SUNGAI ALAT', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'SUNGAI TUAN ILIR', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'SUNGAI TUAN ULU', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'TAMBAK DANAU', 'kecamatan' => 'ASTAMBUL'],
            ['kelurahan' => 'TAMBANGAN', 'kecamatan' => 'ASTAMBUL'],

            ['kelurahan' => 'BABIRIK', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'HANDIL PURAI', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'HAUR KUNING', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'JAMBU BURUNG', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'JAMBU RAYA', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'KAMPUNG BARU', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'LAWAHAN', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'MUARA HALAYUNG', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'PINDAHAN BARU', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'RUMPIANG', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'SALAT MAKMUR', 'kecamatan' => 'BERUNTUNG BARU'],
            ['kelurahan' => 'TAMBAK PADI', 'kecamatan' => 'BERUNTUNG BARU'],

            ['kelurahan' => 'ALALAK PADANG', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'BENUA ANYAR', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'CINTAPURI', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'GARIS HANYAR', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'KARYA MAKMUR', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'KERAMAT MINA', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'MAKMUR KARYA', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'SIMPANG LIMA', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'SINDANG JAYA', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'SUMBER SARI', 'kecamatan' => 'CINTAPURI DARUSSALAM'],
            ['kelurahan' => 'SURIAN HANYAR', 'kecamatan' => 'CINTAPURI DARUSSALAM'],

            ['kelurahan' => 'BANYU HIRANG', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'GAMBUT', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'GAMBUT BARAT', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'GUNTUNG PAPUYU', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'GUNTUNG UJUNG', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'KAYU BAWANG', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'KELADAN BARU', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'MAKMUR', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'MALINTANG', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'MALINTANG BARU', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'SUNGAI KUPANG', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'TAMBAK SIRANG DARAT', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'TAMBAK SIRANG BARU', 'kecamatan' => 'GAMBUT'],
            ['kelurahan' => 'TAMBAK SIRANG LAUT', 'kecamatan' => 'GAMBUT'],

            ['kelurahan' => 'ABIRAU', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'AWANG BANGKAL BARAT', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'AWANG BANGKAL TIMUR', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'JINGAH HABANG ILIR', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'JINGAH HABANG ULU', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'KARANG INTAN', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'KIRAM', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'LIHUNG', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'LOK TANGGA', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'MALI MALI', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'MANDIANGIN BARAT', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'MANDIANGIN TIMUR', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'MANDIKAPAU BARAT', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'MANDIKAPAU TIMUR', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'PADANG PANJANG', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'PANDAK DAUN', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'PASAR LAMA', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'PENYAMBARAN', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'PULAU NYIURG', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'SUNGAI ALANG', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'SUNGAI ARFAT', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'SUNGAI ASAM', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'SUNGAI LANDAS', 'kecamatan' => 'KARANG INTAN'],
            ['kelurahan' => 'SUNGAI BESAR', 'kecamatan' => 'KARANG INTAN'],

            ['kelurahan' => 'BANUA HANYAR', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'BELAYUNG BARU', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'KERTAK HANYAR I', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'KERTAK HANYAR II', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'MANARAP BARU', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'MANARAP LAMA', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'MANARAP TENGAH', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'MANDARSARI', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'MEKAR RAYA', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'PASAR KAMIS', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'SIMPANG EMPAT', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'SUNGAI LAKUM', 'kecamatan' => 'KERTAK HANYAR'],
            ['kelurahan' => 'TATAH PEMANGKIH LAUT', 'kecamatan' => 'KERTAK HANYAR'],

            ['kelurahan' => 'BINCAU', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'BINCAU MUARA', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'CINDAI ALUS', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'INDRASARI', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'JAWA', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'JAWA LAUT', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'KERATON', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'LABUAN TABU', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'MURUNG KENANGA', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'MURUNG KERATON', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'PASAYANGAN', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'PASAYANGAN BARAT', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'PASAYANGAN SELATAN', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'PASAYANGAN UTARA', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'SEKUMPUL', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'SUNGAI PARING', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'SUNGAI SIPAI', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TAMBAK BARU', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TAMBAK BARU ILIR', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TAMBAK BARU ULU', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TANJUNG REMA', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TANJUNG REMA DARAT', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TUNGGUL IRANG', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TUNGGUL IRANG ILIR', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TUNGGUL IRANG ULU', 'kecamatan' => 'MARTAPURA'],
            ['kelurahan' => 'TUNGKARAN', 'kecamatan' => 'MARTAPURA'],

            ['kelurahan' => 'ANTASAN SUTUN', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'KELILING BENTENG TENGAH', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'KELILING BENTENG ULU', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'PENGGALAMAN', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'SUNGAI BATANG', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'SUNGAI BATANG ILIR', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'SUNGAI RANGAS', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'SUNGAI RANGAS HAMBUKU', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'SUNGAI RANGAS TENGAH', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'SUNGAI RANGAS ULU', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'TANGKAS', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'TELUK SELONG', 'kecamatan' => 'MARTAPURA BARAT'],
            ['kelurahan' => 'TELUK SELONG ULU', 'kecamatan' => 'MARTAPURA BARAT'],

            ['kelurahan' => 'AKAR BAGANTUNG', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'AKAR BARU', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'ANTASAN SENOR', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'ANTASAN SENOR ILIR', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'DALAM PAGAR', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'DALAM PAGAR ULU', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'KERAMAT', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'KERAMAT BARU', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'MEKAR', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'MELAYU', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'MELAYU ILIR', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'MELAYU TENGAH', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'PEKAUMAN', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'PEKAUMAN DALAM', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'PEKAUMAN ULU', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'PEMATANG BARU', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'SUNGAI KITANO', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'TAMBAK ANYAR', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'TAMBAK ANYAR ILIR', 'kecamatan' => 'MARTAPURA TIMUR'],
            ['kelurahan' => 'TAMBAK ANYAR ULU', 'kecamatan' => 'MARTAPURA TIMUR'],

            ['kelurahan' => 'BARU', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'BAWAHAN PASAR', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'BAWAHAN SEBERANG', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'BAWAHAN SELAN', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'GUNUNG ULIN', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'LOK TAMU', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'MANGKALAWAT', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'MATARAMAN', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'PASIRAMAN', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'PEMATANG DANAU', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'SIMPANG TIGA', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'SUNGAI JATI', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'SURIAN', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'TAKUTI', 'kecamatan' => 'MATARAMAN'],
            ['kelurahan' => 'TANAH ABANG', 'kecamatan' => 'MATARAMAN'],

            ['kelurahan' => 'ANGKIPIH', 'kecamatan' => 'PARAMASAN'],
            ['kelurahan' => 'PARAMASAN ATAS', 'kecamatan' => 'PARAMASAN'],
            ['kelurahan' => 'PARAMASAN BAWAH', 'kecamatan' => 'PARAMASAN'],
            ['kelurahan' => 'REMO', 'kecamatan' => 'PARAMASAN'],

            ['kelurahan' => 'ALIMUKIM', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'ANTARAKU', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => "ATI'IM", 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'BENTENG', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'KERTAK EMPAT', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'LOBANG BARU', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'LOK TUNGGUL', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'LUMPANGI', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'MANGKAUK', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'MANIAPUN', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'PANYIURAN', 'kecamatan' => 'PENGARON'],
            ['kelurahan' => 'PENGARON', 'kecamatan' => 'PENGARON'],

            ['kelurahan' => 'BALIANGIN', 'kecamatan' => 'SAMBUNG MAKMUR'],
            ['kelurahan' => 'BATANG BANYU', 'kecamatan' => 'SAMBUNG MAKMUR'],
            ['kelurahan' => 'BATU TANAM', 'kecamatan' => 'SAMBUNG MAKMUR'],
            ['kelurahan' => 'GUNUNG BATU', 'kecamatan' => 'SAMBUNG MAKMUR'],
            ['kelurahan' => 'MADUREJO', 'kecamatan' => 'SAMBUNG MAKMUR'],
            ['kelurahan' => 'PASAR BARU', 'kecamatan' => 'SAMBUNG MAKMUR'],
            ['kelurahan' => 'SUNGAI LURUS', 'kecamatan' => 'SAMBUNG MAKMUR'],

            ['kelurahan' => 'PASAR LAMA', 'kecamatan' => 'SIMPANG EMPAT'],
            ['kelurahan' => 'SIMPANG EMPAT', 'kecamatan' => 'SIMPANG EMPAT'],
            ['kelurahan' => 'SUNGAI LANGSAT', 'kecamatan' => 'SIMPANG EMPAT'],
            ['kelurahan' => 'SUNGAI RAYA', 'kecamatan' => 'SIMPANG EMPAT'],
            ['kelurahan' => 'SUNGAI TABUK', 'kecamatan' => 'SIMPANG EMPAT'],
            ['kelurahan' => 'SUNGKAI', 'kecamatan' => 'SIMPANG EMPAT'],
            ['kelurahan' => 'SUNGKAI BARU', 'kecamatan' => 'SIMPANG EMPAT'],
            ['kelurahan' => 'TANAH INTAN', 'kecamatan' => 'SIMPANG EMPAT'],

            ['kelurahan' => 'BELIMBING BARU', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'BELIMBING LAMA', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'HAKIM MAKMUR', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'KAHELAAN', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'KUPANG REJO', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'PAKUTIK', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'RANTAU BAKULA', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'RANTAU NANGKA', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'SUMBER BARU', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'SUMBER HARAPAN', 'kecamatan' => 'SUNGAI PINANG'],
            ['kelurahan' => 'SUNGAI PINANG', 'kecamatan' => 'SUNGAI PINANG'],

            ['kelurahan' => 'ABUMBUN JAYA', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'GUDANG HIRANG', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'GUDANG TENGAH', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'KELILING BENTENG ILIR', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'LOK BAINTAN', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'LOK BAINTAN DALAM', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'LOK BUNTAR', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'PAKU ALAM', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'PEJAMBUAN', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'PEMAKUAN', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'PEMATANG PANJANG', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'PEMBANTANAN', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SUNGAI BAKUNG', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SUNGAI BANGKAL', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SUNGAI LULUT', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SUNGAI PINANG BARU', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SUNGAI PINANG LAMA', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SUNGAI TABUK KERAMAT', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SSUNGAI TABUK KOTA', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'SUNGAI TANDIPAH', 'kecamatan' => 'SUNGAI TABUK'],
            ['kelurahan' => 'TAJAU LANDUNG', 'kecamatan' => 'SUNGAI TABUK'],

            ['kelurahan' => 'BANGKAL TENGAH', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'JARUJU LAUT', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'LAYAP BARU', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'MEKAR SARI', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'PANDAN SARI', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'PEMANGKIH BARU', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'PEMANGKIH DARAT', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'PEMANGKIH TENGAH', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'TAMPANG AWANG', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'TATAH BANGKAL', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'TATAH JARUJU', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'TATAH LAYAP', 'kecamatan' => 'TATAH MAKMUR'],
            ['kelurahan' => 'THAIBAH RAYA', 'kecamatan' => 'TATAH MAKMUR'],

            ['kelurahan' => 'LOK TANAH', 'kecamatan' => 'TELAGA BAUNTUNG'],
            ['kelurahan' => 'RAMPAH', 'kecamatan' => 'TELAGA BAUNTUNG'],
            ['kelurahan' => 'RANTAU BUJUR', 'kecamatan' => 'TELAGA BAUNTUNG'],
            ['kelurahan' => 'TELAGA BARU', 'kecamatan' => 'TELAGA BAUNTUNG'],

            ['kelurahan' => 'BELANDEAN', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'BELANDEAN MUARA', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'BERANGAS', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'BERANGAS BARAT', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'BERANGAS TIMUR', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'BERINGIN', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'HANDIL BAKTI', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'PANCA KARYA', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'PULAU ALALAK', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'PULAU SEWANGI', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'PULAU SUGARA', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'SEI SEMANGAT BHAKTI', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'SEMANGAT DALAM', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'SEMANGAT KARYA', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'SUNGAI LUMBAH', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'SUNGAI PITUNG', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'TANJUNG HARAPAN', 'kecamatan' => 'ALALAK'],
            ['kelurahan' => 'TATAH MESJID', 'kecamatan' => 'ALALAK'],

            ['kelurahan' => 'ANJIR MUARA KOTA', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'ANJIR MUARA KOTA TENGAH', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'ANJIR MUARA LAMA', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'ANJIR SERAPAT BARU', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'ANJIR SERAPAT BARU I', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'ANJIR SERAPAT LAMA', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'ANJIR SERAPAT MUARA', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'ANJIR SERAPAT MUARA I', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'BERINGIN JAYA', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'MARABAHAN BARU', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'PATIH MUHUR', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'PATIH MUHUR BARU', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'SEPAKAT BARSAMA', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'SUNGAI PUNGGU', 'kecamatan' => 'ANJIR MUARA'],
            ['kelurahan' => 'SUNGAI PUNGGU BARU', 'kecamatan' => 'ANJIR MUARA'],

            ['kelurahan' => 'ANDAMAN', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'ANDAMAN II', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'ANJIR PASAR KOTA', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'ANJIR PASAR KOTA II', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'ANJIR PASAR LAMA', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'ANJIR SEBERANG PASAR I', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'ANJIR SEBERANG PASAR II', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'BANYIUR', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'BARUNAI BARU', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'DANAU KARYA', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'GANDARAYA', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'GANDARIA', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'HILIR MESJID', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'MENTAREN', 'kecamatan' => 'ANJIR PASAR'],
            ['kelurahan' => 'PANDAN SARI', 'kecamatan' => 'ANJIR PASAR'],

            ['kelurahan' => 'BAHALAYUNG', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'BALUKUNG', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'BANITAN', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'BANUA ANYAR', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'BATIK', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'LEPASAN', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'MURUNG RAYA', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'PALINGKAU', 'kecamatan' => 'BAKUMPAI'],
            ['kelurahan' => 'SUNGAI SELIRIK', 'kecamatan' => 'BAKUMPAI'],

            ['kelurahan' => 'BAGAGAP', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'BARAMBAI', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'BARAMBAI KARYA TANI', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'BARAMBAI KOLAM KANAN', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'BARAMBAI KOLAM KIRI', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'BARAMBAI KOLAM KIRI DALAM', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'HANDIL BARABAI', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'KARYA BARU', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'PENDALAMAN', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'PENDALAMAN BARU', 'kecamatan' => 'BARAMBAI'],
            ['kelurahan' => 'SUNGAI KALI', 'kecamatan' => 'BARAMBAI'],

            ['kelurahan' => 'BAMBANGIN', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'BELAWANG', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'BINAAN BARU', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'KARANG BUAH', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'KARANG DUKUH', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'MURUNG KERAMAT', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'PARIMATA', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'PATIH SELERA', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'RANGGA SURYA', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'SAMUDA', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'SUKARAMAI', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'SUNGAI SELUANG', 'kecamatan' => 'BELAWANG'],
            ['kelurahan' => 'SUNGAI SELUANG PASAR', 'kecamatan' => 'BELAWANG'],

            ['kelurahan' => 'BADANDAN', 'kecamatan' => 'CERBON'],
            ['kelurahan' => 'BANTUIL', 'kecamatan' => 'CERBON'],
            ['kelurahan' => 'SAWAHAN', 'kecamatan' => 'CERBON'],
            ['kelurahan' => 'SEI RAYA', 'kecamatan' => 'CERBON'],
            ['kelurahan' => 'SEI TUNJANG', 'kecamatan' => 'CERBON'],
            ['kelurahan' => 'SIMPANG NUNGKI', 'kecamatan' => 'CERBON'],
            ['kelurahan' => 'SUNGAI KAMBAT', 'kecamatan' => 'CERBON'],
            ['kelurahan' => 'SUNGAI RASAU', 'kecamatan' => 'CERBON'],

            ['kelurahan' => 'BAHANDANG', 'kecamatan' => 'JEJANGKIT'],
            ['kelurahan' => 'CAHAYA BARU', 'kecamatan' => 'JEJANGKIT'],
            ['kelurahan' => 'JEJANGKIT BARAT', 'kecamatan' => 'JEJANGKIT'],
            ['kelurahan' => 'JEJANGKIT MUARA', 'kecamatan' => 'JEJANGKIT'],
            ['kelurahan' => 'JEJANGKIT PASAR', 'kecamatan' => 'JEJANGKIT'],
            ['kelurahan' => 'JEJANGKIT TIMUR', 'kecamatan' => 'JEJANGKIT'],
            ['kelurahan' => 'SAMPURNA', 'kecamatan' => 'JEJANGKIT'],

            ['kelurahan' => 'ASIA BARU', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'JAMBU', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'JAMBU BARU', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'JARENANG', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'KABUAU', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'KURIPAN', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'RIMBUN TULANG', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'TABATAN', 'kecamatan' => 'KURIPAN'],
            ['kelurahan' => 'TABATAN BARU', 'kecamatan' => 'KURIPAN'],

            ['kelurahan' => 'ANTASAN SEGERA', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'BANGKIT BARU', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'KARANG BUNGA', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'KARANG INDAH', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'LOKRAWA', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'PANTAI HAMBAWANG', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'PUNTIK DALAM', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'PUNTIK LUAR', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'PUNTIK TENGAH', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'SEI RAMANIA', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'TABING RIMBAH', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'TANIPAH', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'TATAH ALAYUNG', 'kecamatan' => 'MANDASTANA'],
            ['kelurahan' => 'TERANTANG', 'kecamatan' => 'MANDASTANA'],

            ['kelurahan' => 'ANTAR BARU', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'ANTAR JAYA', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'ANTAR RAYA', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'BAGUS', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'BALIUK', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'KARYA MAJU', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'MARABAHAN KOTA', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'PENGHULU', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'SIDO MAKMUR', 'kecamatan' => 'MARABAHAN'],
            ['kelurahan' => 'ULU BENTENG', 'kecamatan' => 'MARABAHAN'],

            ['kelurahan' => 'INDAH SARI', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'JELAPAT II', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'KARANG MEKAR', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'MEKARSARI', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'TAMBAN RAYA', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'TAMBAN RAYA BARU', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'TINGGIRAN BARU', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'TINGGIRAN DARAT', 'kecamatan' => 'MEKARSARI'],
            ['kelurahan' => 'TINGGIRAN TENGAH', 'kecamatan' => 'MEKARSARI'],

            ['kelurahan' => 'DANDA JAYA', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'PINDAHAN BARU', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'SIMPANG ARJA', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'SINAR BARU', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'TSUNGAI BAMBAN', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'SUNGAI GAMPA', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'SUNGAI GAMPA ASAHI', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'SUNGAI PANTAI', 'kecamatan' => 'RANTAU BADAUH'],
            ['kelurahan' => 'SUNGAI SAHURAI', 'kecamatan' => 'RANTAU BADAUH'],

            ['kelurahan' => 'BANDAR KARYA', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'KARYA INDAH', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'KARYA MAKMUR', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'MUARA PULAU', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'PANTANG BARU', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'PANTANG RAYA', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'RANTAU BAMBAN', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'TABUKAN RAYA', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'TAMBA JAYA', 'kecamatan' => 'TABUKAN'],
            ['kelurahan' => 'TELUK TAMBA', 'kecamatan' => 'TABUKAN'],

            ['kelurahan' => 'BERINGIN KENCANA', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'KARYA BARU', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'KUALA LUPAK', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'SUNGAI JINGAH BESAR', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'SUNGAI TELAN BESAR', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'SUNGAI TELAN KECIL', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'SUNGAI TELAN MUARA', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'SUNGAI TERAS DALAM', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'SUNGAI TERAS LUAR', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'TABUNGANEN KECIL', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'TABUNGANEN MUARA', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'TABUNGANEN PEMURUS', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'TABUNGANEN TENGAH', 'kecamatan' => 'TABUNGANEN'],
            ['kelurahan' => 'TANGGUL REJO', 'kecamatan' => 'TABUNGANEN'],

            ['kelurahan' => 'DAMSARI', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'JELAPAT BARU', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'JELAPAT I', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'KOANDA', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'PURWOSARI BARU', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'PURWOSARI I', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'PURWOSARI II', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'SEKATA BARU', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'SIDOREJO', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'TAMBAN BANGUN', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'TAMBAN BANGUN BARU', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'TAMBAN KECIL', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'TAMBAN MUARA', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'TAMBAN MUARA BARU', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'TAMBAN SARI BARU', 'kecamatan' => 'TAMBAN'],
            ['kelurahan' => 'TINGGIRAN II LUAR', 'kecamatan' => 'TAMBAN'],

            ['kelurahan' => 'BABAT RAYA', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'DWIPASARI', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'KOLAM KANAN', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'KOLAM KIRI', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'KOLAM MAKMUR', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'PINANG HABANG', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'ROHAM RAYA', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'SIDOMULYO', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'SIMPANG JAYA', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'SUMBER RAHAYU', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'SURYA KANTA', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'TUMIH', 'kecamatan' => 'WANARAYA'],
            ['kelurahan' => 'WARINGIN KENCANA', 'kecamatan' => 'WANARAYA'],


        ];

        Kelurahan::insert($kelurahan);
    }
}
